//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrossReference
{
    using System;
    using System.Collections.Generic;
    
    public partial class CARREFERENCES
    {
        public int LOGICALREF { get; set; }
        public string URETICI { get; set; }
        public string MODEL { get; set; }
        public string MODELTIPI { get; set; }
        public string MOTORGUCU { get; set; }
        public string URETIMYILI { get; set; }
        public string YAKIT { get; set; }
        public string ALAN1 { get; set; }
        public string ALAN11 { get; set; }
        public string ALAN12 { get; set; }
        public string ALAN13 { get; set; }
        public string ALAN14 { get; set; }
        public string ALAN15 { get; set; }
        public string ALAN16 { get; set; }
        public string ALAN17 { get; set; }
        public string ALAN18 { get; set; }
        public string ALAN19 { get; set; }
    }
}
