//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrossReference
{
    using System;
    using System.Collections.Generic;
    
    public partial class CROSS
    {
        public int ID { get; set; }
        public string ITEMCODE { get; set; }
        public Nullable<int> CLASS { get; set; }
        public string MARKA { get; set; }
        public string ARAC_TURU { get; set; }
    }
}
